CREATE DATABASE [Quanlykho]
 CONTAINMENT= NONE
 ON  PRIMARY 
( NAME = N'Quanlykho', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\Quanlykho.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Quanlykho_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\Quanlykho_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Quanlykho].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Quanlykho] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Quanlykho] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Quanlykho] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Quanlykho] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Quanlykho] SET ARITHABORT OFF 
GO

ALTER DATABASE [Quanlykho] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Quanlykho] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Quanlykho] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Quanlykho] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Quanlykho] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Quanlykho] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Quanlykho] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Quanlykho] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Quanlykho] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Quanlykho] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Quanlykho] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Quanlykho] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Quanlykho] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Quanlykho] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Quanlykho] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Quanlykho] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Quanlykho] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Quanlykho] SET RECOVERY FULL 
GO

ALTER DATABASE [Quanlykho] SET  MULTI_USER 
GO

ALTER DATABASE [Quanlykho] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Quanlykho] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Quanlykho] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Quanlykho] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Quanlykho] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Quanlykho] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Quanlykho] SET  READ_WRITE 
GO