CREATE DATABASE [QLThuVienHVKTQS]
 CONTAINMENT= NONE
 ON  PRIMARY 
( NAME = N'QLThuVienHVKTQS', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\QLThuVienHVKTQS.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'QLThuVienHVKTQS_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\QLThuVienHVKTQS_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [QLThuVienHVKTQS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [QLThuVienHVKTQS] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [QLThuVienHVKTQS] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [QLThuVienHVKTQS] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [QLThuVienHVKTQS] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [QLThuVienHVKTQS] SET ARITHABORT OFF 
GO

ALTER DATABASE [QLThuVienHVKTQS] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [QLThuVienHVKTQS] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [QLThuVienHVKTQS] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [QLThuVienHVKTQS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [QLThuVienHVKTQS] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [QLThuVienHVKTQS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [QLThuVienHVKTQS] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [QLThuVienHVKTQS] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [QLThuVienHVKTQS] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [QLThuVienHVKTQS] SET  DISABLE_BROKER 
GO

ALTER DATABASE [QLThuVienHVKTQS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [QLThuVienHVKTQS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [QLThuVienHVKTQS] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [QLThuVienHVKTQS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [QLThuVienHVKTQS] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [QLThuVienHVKTQS] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [QLThuVienHVKTQS] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [QLThuVienHVKTQS] SET RECOVERY FULL 
GO

ALTER DATABASE [QLThuVienHVKTQS] SET  MULTI_USER 
GO

ALTER DATABASE [QLThuVienHVKTQS] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [QLThuVienHVKTQS] SET DB_CHAINING OFF 
GO

ALTER DATABASE [QLThuVienHVKTQS] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [QLThuVienHVKTQS] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [QLThuVienHVKTQS] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [QLThuVienHVKTQS] SET QUERY_STORE = OFF
GO

ALTER DATABASE [QLThuVienHVKTQS] SET  READ_WRITE 
GO